version: '3'

services:
    php:
      build:
        context: .
        dockerfile: php.dockerfile
      container_name: ptphp
      volumes:
        - ./:/var/www/html
      networks:
            patterns-app-network:
                ipv4_address: 11.0.0.9

networks:
    patterns-app-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "11.0.0.0/16"