version: '3'

services:
    php:
      build:
        context: .
        dockerfile: php.dockerfile
      volumes:
        - ./:/var/www/html
      networks:
        - app-network

networks:
  app-network:
    driver: bridge